language: ruby
rvm:
  - 2.6.3
services:
- docker
before_install:
- docker build .
- gem update --system
- gem install bundler
script:
- bundle exec rspec
- bundle exec bundle audit
- bundle exec rubocop
